package dev.gaphunter.nginxcompanion.directives

data class NginxDirective(val name: String, val module: String)

/**
 * Loads the bundled catalog of real nginx directives (fetched from
 * nginx.org's official directive index, one per module) from
 * `resources/directives/nginx_directives.json`. The JSON is generated by
 * our own script, not user input, and has a fixed flat shape
 * (`[{"name":"...","module":"..."}, ...]`), so a couple of targeted
 * regexes are enough — pulling in a JSON library for this one bundled,
 * trusted file would be a much bigger dependency than the plugin itself.
 */
object NginxDirectiveIndex {

    private val ENTRY_PATTERN = Regex("\"name\":\"([^\"]*)\",\"module\":\"([^\"]*)\"")

    val directives: List<NginxDirective> by lazy { load() }

    val names: Set<String> by lazy { directives.map { it.name }.toSet() }

    fun isKnownDirective(word: String): Boolean = word in names

    private fun load(): List<NginxDirective> {
        val stream = javaClass.getResourceAsStream("/directives/nginx_directives.json")
            ?: return emptyList()
        val json = stream.use { it.readBytes().toString(Charsets.UTF_8) }
        return ENTRY_PATTERN.findAll(json).map { m -> NginxDirective(m.groupValues[1], m.groupValues[2]) }.toList()
    }
}
